### ISSUE TITLE
Overcut option?

### ISSUE THREAD

**Issue by narvf** [vilemnovak/blendercam#20]
Is it possible to add an overcut option in corners? I have no experience in programming. 
This is useful for example in plywood when i have two or more elements to put on inside another.

Like here for example
http://www.cambam.info/doc/plus/images/overcut.png

**Comment by vilemnovak** [comment]
Since there are so many overcut options, I so far decided not to try to add this feature. It would have to have manual input anyway probably...

**Comment by nfz** [comment]
I do it manually using the drill strategy as an operation.  I just mark all the corners that need overcut and do it as a chained operation.  I use a circle curve the diameter of the bit (usually an end mill) and then its easy to place exactly on the corner.  Just use alt-D to clone the curve while in edit mode for each corner and move the curve on the z axis to the depth of cut needed.  I guess if you have a lot of corners to do then automating it would be faster.

**Comment by vilemnovak** [comment]
Well it would, especially also because the overcut is correct when you do not put a circle in the corner, you just need to touch the corner with the side of the circle. I always thought about overcuts as part of design, not relaly something CAM should do...

**Comment by narvf** [comment]
Great idea nfz. I do my projects in inkscape and the import svg filem. Se it's not such a big problem to add circles and use drill option :)

**Comment by vilemnovak** [comment]
Hi, just commited overcuts operator.
Select curve or text object - hit space, write overcut.

Let me know if this works correctly.

**Comment by nfz** [comment]
Checking it out...

**Comment by nfz** [comment]
I must be missing something.  I set up a square using a bezier circle and applied the overcuts operator.  A curve is created with the identical shape (a square).  I played with the diamter and threshold and can see in the terminal window new calculations being done but no change in the shape.
![overcuttest](https://cloud.githubusercontent.com/assets/648108/12345921/83b5c5f2-bb25-11e5-864a-35aae1b8e706.png)


[blendercamovercut.blend.zip](https://github.com/vilemnovak/blendercam/files/91374/blendercamovercut.blend.zip)

I will keep playing and take a look at the code.  Probably silly user error.

**Comment by vilemnovak** [comment]
just check also outer polygons option. - it is quite logical to make the overcuts only in holes, and your shape doesn't have any hole - the algorithm assumes it is working on  a whole shape which is to be cut. If you check the

**Comment by vilemnovak** [comment]
hm ok - so the algo is written this way - it adds overcuts only to inner angles. I will add an invert option, where it's assumed that you actually want to create only the hole.
Test it with some text object to see how it works now..

**Comment by vilemnovak** [comment]
also, remember you can always use the Intarsion operator, which is there to make perfect inlays - shapes that can be milled both from inside and from outside.

**Comment by vilemnovak** [comment]
changed this and now things should give more sense. 
here you can see inner/outer overcuts, vs intarsion operator result:
![image](https://cloud.githubusercontent.com/assets/6907354/12347837/fc4d34dc-bb61-11e5-9374-65f9e725b1e7.png)

**Comment by nfz** [comment]
Cool.  My test case works now.  Thanks.  I will play some more with this then update the wiki.  Its definitely a lot faster this way than the way I was doing it.  Greatly appreciate this.

**Comment by narvf** [comment]
Great. I will check this in free time.
Thank you.

**Comment by schef** [comment]
Hey guys. I'm just trying this out and am not sure how to use this when i have an mash object for example a cube 20x20x3 with inside hole which is 5x5x3. is there a way to apply overcuts to cam path?

**Comment by vilemnovak** [comment]
Use curve objects.

**Comment by schef** [comment]
Should i convert my whole object to curve? Or just use a 2d curve?

**Comment by schef** [comment]
Are there some sugesstions to overcome this specific problem. I am trying to use blender only but am not sure how to make cornerovecut on the mesh objects. Any sugestions would be appreciated (also workaronds).

**Comment by nfz** [comment]
Could you post an image of the mesh and the cam path?

**Comment by schef** [comment]
So my tool is 3.5mm

![blendercam_overcut_mesh](https://cloud.githubusercontent.com/assets/775502/12606692/9e231e90-c4cf-11e5-8105-f98306d121a8.gif)

**Comment by vilemnovak** [comment]
this is a perfect case for doing it as a curve, not as a mesh object...
-Create a curve
-use overcut operator on it,
-use the result curve for your profile operation.
I am closing this as an "issue", since I consider this now more a support topic, which should be handled in the forum.
