### ISSUE TITLE
operation starts below surface and not at 10mm as before.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [vilemnovak/blendercam#3]
```
See the attached blend file and the cutter starting below surface (-6mm) for 
the "trous_retournement" operation.

Same for the "trou_pos" operation, starting at +7mm instead of +10mm
```

Original issue reported on code.google.com by `gael.cam...@gmail.com` on 11 Mar 2015 at 10:27

Attachments:
* [big_error_latest_svn.blend](https://storage.googleapis.com/google-code-attachments/blendercam/issue-3/comment-0/big_error_latest_svn.blend)

**Comment by nfz** [comment]
I tested the blend file and it seems to work correctly now. Starts at +10mm for both operations.  I had to do two things: select Drill for the Cam operation strategy, and delete the original path and then select Calculate Path.  I was using github Blendercam updated 26 Oct 2015.

**Comment by vilemnovak** [comment]
works ok here too, closing.
