### ISSUE TITLE
Pack curves on sheet - not working

### ISSUE THREAD

**Issue by narvf** [vilemnovak/blendercam#42]
[curves-on-sheet.blend.zip](https://github.com/vilemnovak/blendercam/files/201270/curves-on-sheet.blend.zip)

Blender file attached.
I've used blender 2.69

Here is the output from console:

> Traceback (most recent call last):
>   File "/home/narvf/Pulpit/blendercam-master/scripts/addons/cam/ops.py", line 253, in execute
>     pack.packCurves()
>   File "/home/narvf/Pulpit/blendercam-master/scripts/addons/cam/pack.py", line 119, in packCurves
>     if allpoly.disjoint(ptrans):
> AttributeError: 'PreparedGeometry' object has no attribute 'disjoint'
> 
> location: <unknown location>:-1
>

**Comment by nfz** [comment]
I get the same error with your blend in Blender 2.77 running Blendercam 9.1.  Definite bug.

**Comment by nfz** [comment]
Found the problem.  I think Vilem was in the process of speeding things up by using packed geometry but its not complete.

But there is an easy fix to get it back to working but it will be slow again.  If you are up to modifying one line of code then you could have it working again.
Modify line 195 in scripts/addons/cam/pack.y from this:
`allpoly=prepared.prep(sgeometry.MultiPolygon(placedpolys))`
to this:
`allpoly=sgeometry.MultiPolygon(placedpolys)`

Just be warned that if you have a lot of curves it will be slow.

**Comment by nfz** [comment]
I committed the temporary fix to github master if you want to pull from github for the fix.

**Comment by nfz** [comment]
Took a crack at finishing the code to use prepared geometry.  It provides about 30% speed improvement on my machine over the old method.  Still room for improvement since its still slow.  I committed the changes to master if you want to try it out.

**Comment by narvf** [comment]
Yes, now it is working! Thank you!
There is something like svgnest.com, it is also open source - I've discovered it today. Seems to work faster. Maybe source code from there would be useful.
https://github.com/Jack000/SVGnest

**Comment by nfz** [comment]
Thanks for the tip, I will have a look at svgnest.com.

**Comment by vilemnovak** [comment]
sorry guys, seeing this discussion just now.
that was really a stupid bug I didn't check when I was trying to use the prepared geometry all around blenderCAM. thanks for fixing, nfz! 
svgnest indeed looks promissing!
