### ISSUE TITLE
How to disable G43 Tool lenght offset command?

### ISSUE THREAD

**Issue by taras-ko** [vilemnovak/blendercam#43]
Blendercam generates code
T1 M06 G43

I don't have an automatic tool change system. I'm changing tool in semi-automatic way by manually changing tool and probing it and calculating and applying offset difference using g code program. So for my machine

T1 M06 G43 is a bad command, because it applies offset for tool 1 from tool offsets table.

How about to add an option to disable tool management or better to give to user choice add a code snippet for auto tool changing sequence?

**Comment by nfz** [comment]
Its generated by the post processor which is selected in the Cam Machine panel.  Which post processor are you using?

**Comment by taras-ko** [comment]
emc2b I guess.

**Comment by nfz** [comment]
The edge branch now has these features.
https://github.com/vilemnovak/blendercam/tree/edge

**Comment by vilemnovak** [comment]
ok, closing this issue then :)
