### ISSUE TITLE
[feature proposal] Adjustable speed of toolpath.

### ISSUE THREAD

**Issue by taras-ko** [vilemnovak/blendercam#45]
Hi, folks.
I would like to propose use Edge Data "Crease" parameter to manually set the speed machine on "hard" places of toolpath.
This feature will be very useful on the beginning of every toolpath with deep plunge. A tool should mill the groove by cutting the material with all of its cutting surface, it's the most dangerouse circumstance of tool brokening. The next step will be much more easier for tool and we can increase the feedrate.
For example.
Suppose I have a toolpath which begins from deep plunge line, and supplose that the plunge depth and default feedrate are too tough for my tool. Ofcourse somehow we can implement an algorithm which will automatically detect such "hard" path regions and it will appropriatelly set the feedrate. But it's more easily give to the user ability to decide where he can slower/faster the feedrate.
![screenshot_20160409_011502](https://cloud.githubusercontent.com/assets/1148481/14398931/bb33e5aa-fdf0-11e5-90c2-e2d63bc9ba51.png)
I can quickly change 'Crease' parameter by pressing shift+e and moving the mouse. This data would be interpretted by postprocessor to change the feedrate
There is a problem. Crease parameter has range from 0.00 to 1.00. So we should think about formula how to set the feedrate slower/faster using such a range.

What are your suggestions about this enhancement?

**Comment by nfz** [comment]
Interesting use of Crease.  

You can convert the crease value using the following formula to give a +1,-1 range:
`= (crease - 0.5) * 2`

**Comment by taras-ko** [comment]
Even we can use crease 0.0-1.0 range as a coficient to override default feedrate. Say, defauld feed rate would be at 0.5 of a crease. 

Пользователь Jeff Doyle <notifications@github.com> писал:

**Comment by vilemnovak** [comment]
Hi, this feature is allready implemented for 3 axis machining, although it is experimental - you have to set Adjust feedrate with simulation in the Feedrate panel.
This creates a shape key which stores the computed speed adjustments. in the Z axis, you can display the feedrate adjustments when switching to the shape key on the path object.
This feature is however not well tested yet and could use some tweaking...

**Comment by vilemnovak** [comment]
I forgot to write - it also exports the modified feedrates allready.
Edge crease however is also a good idea to visualise the speeds more naturally, however, with big paths, going to editmode might be very hard...

**Comment by taras-ko** [comment]
I thinks we can close this issue it moved to issue #69
