### ISSUE TITLE
Pencyl Strategy problem

### ISSUE THREAD

**Issue by kylotron** [vilemnovak/blendercam#49]
The tool path is not linear

[test.blend.zip](https://github.com/vilemnovak/blendercam/files/224317/test.blend.zip)
![schermata del 2016-04-18 19 19 54](https://cloud.githubusercontent.com/assets/5792338/14613059/d245973c-059a-11e6-9f2d-4b5b2d4bb97e.png)

**Comment by vilemnovak** [comment]
Pencil strategy is not intended for this case... it's intended only for 3d shapes, and not really finished, that's why it's marked experimental.

**Comment by vilemnovak** [comment]
this kind of case would be a pocketing thing...

**Comment by kylotron** [comment]
Ok. Thanks
