### ISSUE TITLE
Imperial unit export broken

### ISSUE THREAD

**Issue by dastultz** [vilemnovak/blendercam#5]
`utils.py` has 2 places that say `'INCH'`. They need to be changed to `'IMPERIAL'` to produce the expected output.

Thanks

**Comment by vilemnovak** [comment]
thanks for noting this, I fixed this and commited. i am quite curious when
this actually got in the repository, have to look at that...

**Comment by dastultz** [comment]
Looks like Denver Hull supplied the patch for this. Not sure what he intended to fix, I hope this doesn't break it...

Did you push? I don't really need you to push, I'm just not all that well versed in Git (I use Mercurial daily) so I'm not sure if I'm doing something wrong.

**Comment by vilemnovak** [comment]
Hi, maybe you'll consider that strange, but I don't precisely know what is it to push  in git :) I call it probably commit, maybe because I used svn before...

**Comment by dastultz** [comment]
Yes, no need for us to squabble over differences in source control systems. My point is that when I go here: https://github.com/vilemnovak/blendercam/commits/master I don't see the commit you are referring to. Like I said, it's not holding me back, but when I see the fix in place I'll close the issue. Thanks!

**Comment by nfz** [comment]
This seems to be fixed.  I switched to imperial and the gcode exported is indeed in imperial when I select imperial in Blendercam.

The commit was here:
https://github.com/vilemnovak/blendercam/commit/64fc0cd8a5190958a4a8fd8bd784b7dacc2d3c14

**Comment by vilemnovak** [comment]
indeed, closed it now
