### ISSUE TITLE
strategy for pockets

### ISSUE THREAD

**Issue by kylotron** [vilemnovak/blendercam#50]
What strategy should I use to implement the attachment piece pockets 1,2,3,4 and 5?

The "piastra 2" operation is perfect!
The "piastra 1" operation, however, I can not calculate it ...

![pezzo](https://cloud.githubusercontent.com/assets/5792338/14792911/e2598098-0b1c-11e6-9c33-5e94aba5ecbc.jpg)

[pezzo.blend.zip](https://github.com/vilemnovak/blendercam/files/235047/pezzo.blend.zip)

**Comment by nfz** [comment]
I can tell you how I do it but don't know if its the best way.  I use a curve object to define the outline of the pocket to be performed and place it at the depth needed to cut the pocket.  So for 1, 2, and 3 I would make 3 curve objects.  The curve object is used for the pocket operation instead of the original object.  With a single core  cpu running at 600 MHz I find this techique very fast for generating the g-code.

For areas 4 and 5 I would use parallel or block operation and use a limiting curve to define the area of operation.

**Comment by nfz** [comment]
Here is an example:
![pocket2](https://cloud.githubusercontent.com/assets/648108/14867695/1ce87ffa-0ca0-11e6-9793-ef6591099233.png)

I went into edit mode on the mesh, selected the edges that define the bottom of the pocket, Shift-D to copy, seperate - to make a new mesh. Then I select the new mesh and convert to curve and rename.  Now I can use that curve for the pocket operation.
![pocket2path](https://cloud.githubusercontent.com/assets/648108/14867823/d136ac5c-0ca0-11e6-93d9-9ee768f22793.png)

**Comment by nfz** [comment]
For area 4 I defined a limit curve just around the area I want to mill:
![limitcurve](https://cloud.githubusercontent.com/assets/648108/14868508/42a240e2-0ca4-11e6-96b3-8035447a3308.png)

I setup a parallel operation using the model and enabled limit curve in the CAM Operation area panel:
![paralop](https://cloud.githubusercontent.com/assets/648108/14868563/961a7ffa-0ca4-11e6-83a1-962ae82e61a4.png)

**Comment by kylotron** [comment]
oh yes, yes, yes.... 

thank's a lot

**Comment by kylotron** [comment]
Pocket_1....

Why i have a most complicated path?

![schermata del 2016-04-29 12 39 11](https://cloud.githubusercontent.com/assets/5792338/14914070/733a7e40-0e07-11e6-89d8-9317f55d2477.png)

**Comment by nfz** [comment]
What are the settings in the CAM optimization panel?  I didn't have OpenCAM lib enabled.

**Comment by kylotron** [comment]
It's same!
![schermata del 2016-04-29 20 38 22](https://cloud.githubusercontent.com/assets/5792338/14926009/60591d2a-0e4a-11e6-83a6-1b7524578d48.png)

[partiinpolicarbonato_1.blend.zip](https://github.com/vilemnovak/blendercam/files/243011/partiinpolicarbonato_1.blend.zip)

**Comment by kylotron** [comment]
My curves for pockets are into other level... :)

**Comment by nfz** [comment]
Just tried the zip you posted and I get the same thing as you.  Investigating....

**Comment by nfz** [comment]
Ok, its a bug in the tool path generation code.  A work around for now is to use overlap of 0.8mm (instead of 1mm that you had) and it will work.

**Comment by vilemnovak** [comment]
Hi, this is NOT a bug. 
Because of the big overlap, there would be uncut areas, so there need to be extra paths which finish those. Sorting of these extra paths is hard, because you need an hierarchy, which is very hard to define with more complex shapes. (any ideas here how to do this?)
Just use overcut =< radius of the tool.

**Comment by vilemnovak** [comment]
Actually, most CAM softwares don't allow overlap larger than half of the cutter  - I was thinking why, only when I was developing the algorithm for detecting and cutting uncut areas, I realized why the coders were lazy to do such a complex thing :)

**Comment by nfz** [comment]
I understand and maybe bug is a poor choice of words for this situation.

**Comment by kylotron** [comment]
![schermata del 2016-05-02 10 26 56](https://cloud.githubusercontent.com/assets/5792338/14950240/7c86b6ee-1050-11e6-8ff3-961985cc9be9.png)

**Comment by kylotron** [comment]
First plate finished!

![piastra_1-1](https://cloud.githubusercontent.com/assets/5792338/14977865/169884ac-1118-11e6-9a14-f86f285be4cd.jpg)
![piastra_1-2](https://cloud.githubusercontent.com/assets/5792338/14977868/169f7366-1118-11e6-8db4-955e49e3a208.jpg)
![piastra_1-3](https://cloud.githubusercontent.com/assets/5792338/14977866/169d5874-1118-11e6-8663-550779142ff9.jpg)
![piastra_1-4](https://cloud.githubusercontent.com/assets/5792338/14977867/169f6894-1118-11e6-9603-70659975283b.jpg)


in picture 2 you see a mistake the edge of the pocket because I had to reposition the piece to fall within the lower limit of the Z! :(

(sorry for my english)

**Comment by kylotron** [comment]
Now there is a "limit" that should be passed ...
A limit curve which allows the processing only on the outside of the curve and not inside!

It's possible?

**Comment by vilemnovak** [comment]
I don't understand what you mean now... there is a limit curve option. Can you explain better?

**Comment by kylotron** [comment]
limit curve option allows RESTRICT operations **INSIDE** of the curve.
It would be useful to have a limit curve for RESTRICT operations **OUTSIDE** of the curve

**Comment by vilemnovak** [comment]
Well, you can define limit curve from 2 curves inside each other, this way you can allready do this.

**Comment by kylotron** [comment]
ok :D

Perfect! ;)

**Comment by kylotron** [comment]
All photos for you!


![piastra_1](https://cloud.githubusercontent.com/assets/5792338/15026039/8e6b55f2-123c-11e6-9c0a-99e7d71af418.jpg)
![piastra_2](https://cloud.githubusercontent.com/assets/5792338/15026041/8e8c782c-123c-11e6-9d8b-12b4c95bea13.jpg)
![piastra_3](https://cloud.githubusercontent.com/assets/5792338/15026043/8ec422b8-123c-11e6-933b-e48039f5b959.jpg)
![piastra_4](https://cloud.githubusercontent.com/assets/5792338/15026042/8ead450c-123c-11e6-80b1-c991c043222b.jpg)
![piastra_5](https://cloud.githubusercontent.com/assets/5792338/15026045/8ee19d48-123c-11e6-8648-b5debdfe4565.jpg)
![piastra_6](https://cloud.githubusercontent.com/assets/5792338/15026044/8edba550-123c-11e6-93a8-9a2c12b59528.jpg)
