### ISSUE TITLE
Error... another... why?

### ISSUE THREAD

**Issue by kylotron** [vilemnovak/blendercam#53]
Same file used yesterday ... parallel strategy applied to the plate with the limit set on a curve ...
And I do not understand why!
I have not updated anything.

> validity 
validity 
validity 
progress{building path pattern}
progress{0.6538865566253662}
convertViewVec: called in an invalid context
Traceback (most recent call last):
  File "/home/kylotron/Scaricati/blendercam/scripts/addons/cam/ops.py", line 218, in execute
    utils.getPath(context,o)
  File "/home/kylotron/Scaricati/blendercam/scripts/addons/cam/utils.py", line 3284, in getPath
    getPath3axis(context,operation)
  File "/home/kylotron/Scaricati/blendercam/scripts/addons/cam/utils.py", line 2854, in getPath3axis
    chunks.extend(sampleChunks(o,pathSamples,layers))
  File "/home/kylotron/Scaricati/blendercam/scripts/addons/cam/utils.py", line 324, in sampleChunks
    getAmbient(o)  
  File "/home/kylotron/Scaricati/blendercam/scripts/addons/cam/utils.py", line 1775, in getAmbient
    polys = curveToShapely(limit_curve)
  File "/home/kylotron/Scaricati/blendercam/scripts/addons/cam/utils.py", line 1364, in curveToShapely
    chunks=curveToChunks(cob)
  File "/home/kylotron/Scaricati/blendercam/scripts/addons/cam/chunk.py", line 813, in curveToChunks
    co = meshFromCurve(o)
  File "/home/kylotron/Scaricati/blendercam/scripts/addons/cam/chunk.py", line 793, in meshFromCurve
    co.data.dimensions='3D'
AttributeError: 'Mesh' object has no attribute 'dimensions'
location: <unknown location>:-1
location: <unknown location>:-1

**Comment by kylotron** [comment]
with Ramp In enabled, have error.

**Comment by nfz** [comment]
Can you post the blend file?

**Comment by nfz** [comment]
ok, found the conditions where this happens.

**Comment by vilemnovak** [comment]
was this fixed?

**Comment by kylotron** [comment]
When i start Blender.... this is the first error:
![schermata del 2016-05-25 10 40 26](https://cloud.githubusercontent.com/assets/5792338/15533484/2417cd32-2265-11e6-8431-da91f2022092.png)

...and when i move the mouse over panel at right of the screen, i have other same errors:
![schermata del 2016-05-25 10 40 37](https://cloud.githubusercontent.com/assets/5792338/15533526/4a7d3f2a-2265-11e6-9d07-ece2f0505a25.png)

When i make a parallel strategy with Ramp In, this is the error:

![schermata del 2016-05-25 10 39 29](https://cloud.githubusercontent.com/assets/5792338/15533449/fb68c21a-2264-11e6-83c1-57052bc38f4c.png)

**Comment by nfz** [comment]
The UI AttributeError has been fixed in Master branch.

The other error in utils.py I also get sometimes when using ramp in.  Not sure what is causing it.

**Comment by nfz** [comment]
Ok, found the problem.  The chunk method rampZigZag() does not return anything but a lot of code in utils.py expects it too.  Will provide a patch for Vilem to review.

**Comment by nfz** [comment]
I committed some bug fixes to Master for ramp in so hopefully this fixes the problems you were having.

**Comment by kylotron** [comment]
![partiinpolicarbonato_1a blend](https://cloud.githubusercontent.com/assets/5792338/15586836/b9fcd500-2386-11e6-8047-768603199040.png)

This is the result of Parallel strategy with Ramp In!

The path is not perfect... but is complite.

**Comment by kylotron** [comment]
No Level...

![partiinpolicarbonato_1a blend 1](https://cloud.githubusercontent.com/assets/5792338/15599982/7b383db2-23e7-11e6-85fe-17ef9f110be9.png)

![partiinpolicarbonato_1a blend 2](https://cloud.githubusercontent.com/assets/5792338/15599981/7b316212-23e7-11e6-893d-fe558540f447.png)
