### ISSUE TITLE
Adding preset not working?

### ISSUE THREAD

**Issue by narvf** [vilemnovak/blendercam#54]
When i was trying to add preset for operation which i was using frequently i got an error
![blender](https://cloud.githubusercontent.com/assets/16607970/15100334/1fcdd526-156f-11e6-8d96-aa70264cd7a1.jpg)

**Comment by nfz** [comment]
Sorry, that's my fault.  Fixing now...

**Comment by nfz** [comment]
Here is the fix:
https://github.com/vilemnovak/blendercam/commit/d6f1ca8693f8184e20a5d0fbe9e5961bcb8d433b
