### ISSUE TITLE
Parallel operation no longer supports parallel stepback

### ISSUE THREAD

**Issue by nfz** [vilemnovak/blendercam#56]
The alternative algorithm that uses numpy which is now the default, does not have code to support parallel stepback.  Will this be added or would a patch be a good idea?

**Comment by nfz** [comment]
There was some talk here:
https://github.com/vilemnovak/blendercam/commit/71f6266f57308b3c51198017505a9977823d80cf

**Comment by vilemnovak** [comment]
fixed this by simply disabling the algo now until it's ready.
