### ISSUE TITLE
 How to make this hole?

### ISSUE THREAD

**Issue by kylotron** [vilemnovak/blendercam#57]
![foro_svasato](https://cloud.githubusercontent.com/assets/5792338/15295634/b5f9a2c8-1b91-11e6-857e-c04c75f82270.png)

**Comment by kylotron** [comment]
This is a countersunk hole (height 5 mm, max diameter 18.4 mm, min diameter 8.4 mm)... 
What strategy should I use? And how should I apply it?

Thank's

**Comment by nfz** [comment]
Maybe circles or spiral using a limit curve?  I usually use a pocket operation for the straight vertical sided sections and then circles or spiral for sloped areas.

**Comment by kylotron** [comment]
I fear it is not easy ...

**Comment by nfz** [comment]
ok, giving it a try....

**Comment by nfz** [comment]
Ok, you win.  I could not get a good path generated with any of the strategies.  Not sure what I am missing or why the strategies give such bad results but will continue investigating.

**Comment by kylotron** [comment]
Ok.
In the meantime I'm writing a parametric gcode to bypass this problem.
But of course it is not "productive" to have to use different gcode to realize a single piece!
I look forward to your developments!

**Comment by nfz** [comment]
With the latest changes that Vilem just committed, I can now use outlinefill strategy to generate a good tool path for this shape.  I did use a limit curve for the perimeter.

**Comment by kylotron** [comment]
I receive this error!
![schermata del 2016-05-24 22 03 57](https://cloud.githubusercontent.com/assets/5792338/15518100/6fbcd99a-21fb-11e6-96fc-02a4b5f49b09.png)

**Comment by kylotron** [comment]
![schermata del 2016-05-24 22 38 15](https://cloud.githubusercontent.com/assets/5792338/15519199/a11b6916-2200-11e6-947a-befb0fbbf0e5.png)

**Comment by nfz** [comment]
Are you using ramp in?

**Comment by kylotron** [comment]
Not Ramp.In... Not Layers... Same Error!

My Zip file is not attached... :(

**Comment by nfz** [comment]
I get that error if the limit curve is not a curve ie I forgot to convert the mesh to a curve.

**Comment by kylotron** [comment]
The result is not perfect!

![test blend](https://cloud.githubusercontent.com/assets/5792338/15616988/1ef153a8-2447-11e6-9704-38f71d3f8604.png)

**Comment by nfz** [comment]
Try it with **Use exact mode** enabled, I get much cleaner results.

**Comment by kylotron** [comment]
Oh yessssssssssssssssssssssssss

![test](https://cloud.githubusercontent.com/assets/5792338/15618007/fe66697a-244b-11e6-84d3-5da9dc221f26.png)
