### ISSUE TITLE
autobridges issue

### ISSUE THREAD

**Issue by ecl66** [vilemnovak/blendercam#61]
Hello Team,

I am trying to use the autobridge function of the profile/cut operation, and get the following error:

read blend: /home/ecl/wifiwater/wifiwater_esp8266_pic18/trunk/esp8266/CAD/enclosure_100/profiling.blend
Traceback (most recent call last):
  File "/opt/blender-2.76b-linux-glibc211-x86_64/2.76/scripts/addons/cam/ops.py", line 687, in execute
    utils.addAutoBridges(o)
  File "/opt/blender-2.76b-linux-glibc211-x86_64/2.76/scripts/addons/cam/utils.py", line 1958, in addAutoBridges
    o.warnings.append('not curves')
AttributeError: 'str' object has no attribute 'append'

location: <unknown location>:-1

location: <unknown location>:-1

Could you please kindly explain the process to correctly use the bridge function (auto or manual)?

Many thanks.

**Comment by vilemnovak** [comment]
this bug was fixed in git, thanks for report though. 
I will probably do a bug fix release soon, seems there were too many bugs in the last version.
In the last version, auto bridges is only for curve objects, so with them you can use them.
