### ISSUE TITLE
[UI improvement proposal] Cam toolpath mesh should be automatically selected on toolpath selection in CAM operations window

### ISSUE THREAD

**Issue by taras-ko** [vilemnovak/blendercam#66]
Thus we can easily navigate through the many toolpathes, and won't be confused. Also we can synchronise life of that object with toolpath in that "CAM operations" panel: If we delete toolpath, then toolpath mesh also must be deleted.

**Comment by nfz** [comment]
+1.  I could start this in a couple of days after I get some cutting done.

**Comment by nfz** [comment]
Started working on this.

If there is no cam path generated then when the operation is selected, the object/group is then selected.

**Comment by nfz** [comment]
This is now in master.

**Comment by taras-ko** [comment]
I found that creating relationship beetween object (Parent) and its cam toolpath mesh (children) is really convenient thing. By [parenting](https://www.blender.org/manual/editors/3dview/object/relationships/parents.html) objects and its toolpathes we can really organize our outliner. Now cam toolpath is folding in as a subnode of object in outliner. Besides 'children' toolpath is synchronously moving with its 'parent' object.

**Comment by nfz** [comment]
+1
That is a really good idea.  Yep, easy to do and will implement.

**Comment by nfz** [comment]
First implementation of parenting is in master.  For now this only works if source of data is an object.  Does not work if source of data is a group or an image.

**Comment by nfz** [comment]
Added some more 3d view selection enhancements.  If the source of data changes or object/group changes then the selection will update.

**Comment by taras-ko** [comment]
Cool, I'll check it.

**Comment by nfz** [comment]
The last thing to be implemented is highlight selection for Chains.  Not sure if it would be beneficial or just cause confusion.
