### ISSUE TITLE
Machine goes to non zero if created without a operation

### ISSUE THREAD

**Issue by TurBoss** [vilemnovak/blendercam#70]
a Machine could be created by the machine menu if no operation is created

but its position seems wrong
http://i.imgur.com/NJ2qpt0.png

not sure if this is a bug thx!

**Comment by nfz** [comment]
Yes, it's a bug.  I will fix it.

**Comment by TurBoss** [comment]
thx!

**Comment by nfz** [comment]
Fix is in master.  Try it out and if it solves the problem then close the issue.  Seems to work correctly now on my machine.
