### ISSUE TITLE
starting point of gcode

### ISSUE THREAD

**Issue by TurBoss** [vilemnovak/blendercam#74]
Hi

how i can define the starting point fo the gcode 
eg= x0 y0 z50 ?

http://imgur.com/P0T6Wd7

**Comment by taras-ko** [comment]
![screenshot_20160706_000957](https://cloud.githubusercontent.com/assets/1148481/16600077/21cef9fa-430e-11e6-8235-4c7c6d8e2abe.png)
Maybe you need g-code header option.
In this example. My machine goes to the safest Z point. (for my machine safest point in machine coordinates is G53 Z0) After that it goes to the x0 y0 of G54 offset, or whatever you'll point. Symbol ';' is like a newline character.

**Comment by TurBoss** [comment]
In my case the piece is independent of the machine coordinates
I place it with g54 on the machine's control panel and the "0" of the piece is the top and center X and Y

thx for your answer
