### ISSUE TITLE
can we have gitter?

### ISSUE THREAD

**Issue by TurBoss** [vilemnovak/blendercam#80]
a chat solution for github repos
as irc is to big for the people we are and issues for questions is not the plan

https://gitter.im/

thx

**Comment by taras-ko** [comment]
I can create a chat room only for my fork ot blendercam. We need to ask vilem to create a chatroom for his repo.
@vilemnovak  Could you please create a chat room for your project? Thanks.

**Comment by vilemnovak** [comment]
There is a blendercam forum. How to create a chat room? Sorry if there is a way to give you rights i'd like to do it since I am completely out of time.

**Comment by taras-ko** [comment]
Unfortunately I can't create a chat room for vilemnovak/blender. I'm not the owner.

**Comment by taras-ko** [comment]
+1 I think we need a chat room with possibility to share the screen.
