### ISSUE TITLE
please help i dont know what to do

### ISSUE THREAD

**Issue by nareknc** [vilemnovak/blendercam#94]
![default](https://cloud.githubusercontent.com/assets/24718707/21430621/5aecd7e4-c87d-11e6-89be-ca51e3bae144.jpg)

**Comment by narvf** [comment]
Can you please explain, what problem do you have? What is your operating system? How did you install/download blendercam?

**Comment by nareknc** [comment]
operating system is ubuntu 14.04.1 and i download and install blendercam  from here https://github.com/vilemnovak/blendercam/wiki/Using-Blendercam-from-github#enable-blendercam-add-on 
and now i dont understand what i am doing wrong

**Comment by narvf** [comment]
Try downloading binary from site blendercam.blogspot.com, https://drive.google.com/drive/folders/0B8_m8tGvVyKpYUVTMm14YWxTWEk
Make sure you have installed:
python-shapely
python-numpy
I don't clearly see the problem. You can not enable plugins? Does blender show some errors?

**Comment by nareknc** [comment]
here is the error 
![2016-12-23 12 11 24](https://cloud.githubusercontent.com/assets/24718707/21449692/76ab866a-c909-11e6-90ab-b533eb8a97aa.jpg)

**Comment by narvf** [comment]
Look slike you don't have installed python-shapely
Maybe ubuntu 14.10 doesn't have this package?

**Comment by vilemnovak** [comment]
Hi, Indeed on ubuntu you need to go to synaptic package manager and install shapely. Since this isn't a bug, closing issue ;)
